### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by DeadFrostt** [adamsol/ChessHue#1]
Holy hell! I just stumbled across this project and its AWESOME I cant believe something like this exists on github LOL. I was wondering if it would be able for you to add a whole chess.com like thing where you can see great moves/brilliant moves it would be very nice to have that. Everything aside, this is a great project thanks for working on this!

**Comment by DeadFrostt** [comment]
Just to clarify, I read the part which states it gives off the move as color, I was thinking of something which makes it easier to distinguish between the moves.

**Comment by adamsol** [comment]
Thanks for the kind words!

Classifying moves like on chess.com was actually how this project started, but I couldn't find satisfying thresholds for the corresponding categories, and I didn't like when e.g. both an unsound sacrifice and hanging checkmate from a winning position were classified the same as a "blunder". And as for great/brilliant moves, I had technical difficulties deciding whether a given move should be considered a sacrifice or special in some other way. Besides, chess.com's classification is also often debatable in this regard. That's why I settled on the current approach without heuristics, and I'm quite happy with how it works in practice.
